language: python
python:
  - 2.7
  - 3.6
arch:
  - amd64
  - arm64
  - ppc64le
before_install:
  - sudo apt-get install -y git wget libtiff-dev
env:
  global:
    - SUDO=""
install:
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      wget -q "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh;
      chmod +x archiconda.sh;
      bash archiconda.sh -b -p $HOME/miniconda;
      SUDO=sudo;
      $SUDO cp -r $HOME/miniconda/bin/* /usr/bin/;
    fi
  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
      wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-ppc64le.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
    else
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda;
      fi
    fi
  - export MINICONDA=$HOME/miniconda
  - hash -r
  - source $MINICONDA/etc/profile.d/conda.sh
  - $SUDO conda config --set always_yes yes --set changeps1 no
  - $SUDO chmod -R 777 $HOME/miniconda/*
  - $SUDO conda update --quiet --yes conda
  - $SUDO conda info -a
  - $SUDO conda env create --quiet --name pylibtiff-dev --file .conda/environment.yml
  - conda activate pylibtiff-dev
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      $SUDO conda install --yes --quiet python=2.7 -c conda-forge;
    fi
  - export PREFIX=$CONDA_PREFIX

before_script:
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
     if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
       sudo chmod -R 777 $HOME/miniconda/envs/pylibtiff-dev/lib/python2.7/site-packages;
     else
       sudo chmod -R 777 $HOME/miniconda/envs/pylibtiff-dev/lib/python3.*/site-packages;
     fi
    fi
  - python setup.py develop

script:
  - pytest -v -r s libtiff/
